first commit week4 homework!
Lidemy/mentor-program-5th-angela1393aa pull request #5
Opened 2021-05-16 14:44 UTC by angela1393aa

提交第四週作業

2021-05-18 14:17 UTC, cwc329 requested changes
基本上 API 串接是有成功的，不錯。
不過有些地方要再改進。

首先，
交作業前請看自我檢討，
並且依照自我檢討訂正作業之後再發 PR，
以後如果有出現明顯沒有達成要求，
或者出現太多自我檢討有提出的問題，
助教有可能不會批改，
並且要求重寫。

還有，
課程裡有 eslint 是要培養一些 coding 的習慣，
目前的階段請依照 eslint 修改報錯的地方，
不要使用 eslint-disable。

最後，
請仔細看作業要求，
在交作業前請一定要檢查是否有達到要求。

2021-05-18 14:17 UTC, cwc329 commented on homeworks/week4/hw1.js
> +// eslint-disable-next-line
為何要 eslint-disable？

2021-05-18 14:17 UTC, cwc329 commented on homeworks/week4/hw1.js
> +  let json
沒有判斷 http status code。

這個在自我檢討裡面有，
請回去看過之後訂正。

2021-05-18 14:17 UTC, cwc329 commented on homeworks/week4/hw2.js
> +    console.log('新增成功！')
你確定只要有 response 就有成功嗎？

2021-05-18 14:17 UTC, cwc329 commented on homeworks/week4/hw3.js
> +  }
沒有題目要求處理錯誤。

2021-05-19 09:54 UTC, cwc329 commented
你的 eslint 錯誤在 terminal 是報什麼錯誤？
可以去 eslint 官網看一下要怎麼解決。

另外就是這週有需要安裝 request 套件，
但是你的 package.json 並沒有更新。

以及 http status code 在所有要處理 http request 的地方都要加，
不是只有我留言的地方。
eslint-disable 也一樣。

2021-05-19 14:51 UTC, WooooHuan reviewed
恭喜完成第四週！
作業有試圖防堵一些例外狀況很不錯，可惜還是有一些些漏網之魚，

在這個階段不強求完全防堵，只要知道有這麼一回事就好，
寫應用程式時，還是要盡可能的顧及，使用者有可能會用預期外的狀況進行操作！

( ~~簡單來說，要把使用者當猴子看待~~ )

大部分的內容 @cwc329 助教都已經 review 完了，
這裡只簡單補充一些目前觀察到的狀況，
時間允許的話，還是建議去訂正一下哦～

---

## hw2 

`read` - ID 不存在時，會印出空物件

`delete` - 即使刪除失敗，也印出刪除成功

`create` - 當指定書名為空時，會創建名為 `undefined` 的書本

`update` - 當更新失敗時，也會印出更新成功

2021-05-19 14:51 UTC, WooooHuan commented on homeworks/week4/hw2.js
> +}
有擋下例外指令，推個~

2021-05-19 14:51 UTC, WooooHuan commented on homeworks/week4/hw2.js
> +  })
這裡使用 `if (err)` 進行例外防堵，可能還是會有漏網之魚哦！

2021-05-19 14:51 UTC, WooooHuan commented on homeworks/week4/hw3.js
> +isName()
有試圖擋下空輸入很不錯！

但是依照 function name 判斷原意，
會讓人覺得 function 會 return 一個關於 name 狀況的 boolean.

我們通常也不會 return console.log() 

是否一開始是想這樣寫呢：

```js
const isName = () => { 
  if (!name) { 
    console.log('請輸入國家名稱') 
  } 
  return !name;
} 
  
if (!isName()) return  // 如名稱為例外狀況，不再執行後續內容

```

2021-05-19 14:51 UTC, merged